version: 0.2

env:
  variables:
    ENVIRONMENT: "development"
  parameter-store:
    DB_PASSWORD: /myapp/develop/db-password
    API_KEY: /myapp/develop/api-key

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
  
  pre_build:
    commands:
      - echo "Running tests..."
      - 'echo "DB_PASSWORD is set: ${DB_PASSWORD:+yes}"'  # Don't print actual password
      - 'echo "API_KEY is set: ${API_KEY:+yes}"'
      - pytest test_app.py -v --cov=app --cov-report=term-missing
  
  build:
    commands:
      - echo "Building application..."
      - mkdir -p build
      - cp * build/
      #- cp requirements.txt build/
      #- cp -r templates build/
  
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: build

cache:
  paths:
    - '/root/.cache/pip/**/*'