version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
  
  pre_build:
    commands:
      - echo "Running tests..."
      - pytest test_app.py -v --cov=app --cov-report=term-missing --cov-report=html
      - echo "Linting code..."
      - pip install flake8
      - flake8 app.py --max-line-length=120 --ignore=E501,W503
      - echo "Security scan..."
      - pip install bandit
      - bandit -r app.py -f json -o bandit-report.json || true
  
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Creating application package..."
      - mkdir -p build
      - cp app.py build/
      - cp requirements.txt build/
      - cp -r templates build/
      - echo "Build completed on `date`"
  
  post_build:
    commands:
      - echo "Post-build phase..."
      - echo "Generating build info..."
      - echo "{\"version\":\"2.0.0\",\"build_date\":\"$(date)\",\"commit\":\"$CODEBUILD_RESOLVED_SOURCE_VERSION\"}" > build/build-info.json
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: build
  name: ecommerce-app-$(date +%Y%m%d-%H%M%S)

reports:
  pytest_reports:
    files:
      - 'htmlcov/index.html'
    file-format: HTML
  coverage_reports:
    files:
      - '.coverage'

cache:
  paths:
    - '/root/.cache/pip/**/*'