version: 0.2

env:
  variables:
    ENVIRONMENT: "development"
  parameter-store:
    DB_PASSWORD: /myapp/develop/db-password
    API_KEY: /myapp/develop/api-key

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
  
  pre_build:
    commands:
      - echo "Running tests..."
      - 'echo "DB_PASSWORD is set: ${DB_PASSWORD:+yes}"'  # Don't print actual password
      - 'echo "API_KEY is set: ${API_KEY:+yes}"'
      - pytest test_app.py -v --cov=app --cov-report=term-missing
  
  build:
    commands:
      - echo "Building application..."
      - echo "Build started on $(date)"
      - chmod +x scripts/*.sh
      - echo "Build completed on $(date)"
  
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
    - appspec.yml
    - app.py
    - requirements.txt
    - 'scripts/**/*'
    - test_app.py
  #discard-paths: no          # Keep directory structure    
  base-directory: BuildArtifact

cache:
  paths:
    - '/root/.cache/pip/**/*'
